feat(bot-22): Add pipeline for ycloud publishing
Education-bot/chatbot_backend pull request #25
Opened 2024-10-21 21:00 UTC by Buckzor110

2024-10-30 20:19 UTC, neevink requested changes

2024-10-30 20:19 UTC, neevink commented on compose.yaml
> +# Comments are provided throughout this file to help you get started.
Давай уберём лишние комментарии и закоментированную конфигурацию контейнера с БД?

2024-10-30 20:19 UTC, neevink commented on compose.yaml
> +      context: .
Тут не должен происходить build, нужно просто поднимать собранный контейнер. Например так:
```yaml
version: '3.7'
services:
  vk-bot:
    image: {{ env.IMAGE_URL }}
    restart: always
    ports:
      - 8080:8080
```

2024-10-30 20:19 UTC, neevink commented on compose.yaml
Давай назовём файл `docker-compose-prod.yaml`?

2024-10-30 20:19 UTC, neevink commented on .github/workflows/image.yml
Давай попробуем разделить этот пайплайн на два разных?
1. PR-check: при новом PR должна происходить сборка проекта и Docker image (просто проверяться, что всё билдится).
2. Deploy to Yandex Cloud: нужно создать воркфлоу, который запускается только вручную (посмотри про `workflow_dispatch`) и выполняет шаги: сборка image, push в docker-registry в Yandex Cloud, деплой на ВМ.

2024-10-30 20:21 UTC, neevink requested changes

2024-10-30 20:21 UTC, neevink commented on .github/workflows/image.yml
> +          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
И опиши ещё пожалуйста в READ.ME про то, какие есть воркфлоу и в частности про то, где брать `YC_SA_JSON_CREDENTIALS`, а то это кажется очень неочевидная штука оказалась.

2024-10-30 20:34 UTC, neevink commented on compose.yaml
> +      - 8080:8080
И, кажется, приложение слушает на 80 порту, стоит уточнить

2024-11-16 12:23 UTC, Buckzor110 commented on compose.yaml
> +      - 8080:8080
Не, там 8080, все норм

2024-12-05 10:08 UTC, neevink commented on .github/workflows/image.yml
> -      #      - name: Checkout repository
это разкомментировать и всё заработает, но будет билдиться 2 раза

2024-12-05 10:09 UTC, neevink commented on .github/workflows/image.yml
> -  workflow_dispatch:
вот тут поправить

2024-12-05 10:11 UTC, neevink commented on .github/workflows/image.yml
>          uses: actions/download-artifact@v4
Доразбираться с джобой Deplou to YCloud

2024-12-16 20:22 UTC, neevink commented on user-data.yaml
Решили пока не делать

2024-12-16 20:24 UTC, neevink approved these changes

2024-12-16 20:24 UTC, neevink commented on .github/workflows/image.yml
> +          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
Попрошу Егора попозже рассказать

2024-12-16 20:25 UTC, merged